pipeline {
    agent any
    tools { 
      maven 'MAVEN_HOME' 
      jdk 'jdk8' 
    }
    stages {
        stage('Build'){
            steps{
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test'){
            steps{
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver'){
            steps {
                sh './jenkins/scripts/deliver.sh'} 
            }
        }
    }

